name: Auto Scrape HIPAA Rules

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once every 24 hours at 00:00 UTC
  workflow_dispatch:      # Manual trigger from GitHub UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run Scraper
      run: python scraper.py

    - name: Commit updated regulations
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add regulations.json
        git commit -m "Update regulations [auto]" || echo "No changes to commit"
        git push
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
